[package]
name = "rustic-vs"
version = "0.1.0"
edition = "2024"
authors = ["Akzyra"]
license = "MIT"
readme = "README.md"

[dependencies]
log = "0.4"
fern = "0.7"
humantime = "2"
humansize = "2"
thiserror = "2"
filenamify = "0.1.2"
freya = { version = "0.5.0-rc.9", features = ["i18n", "router", "icons-lucide", "html"] }
serde = { version = "1", features = ["derive"] }
json5 = "1.3"
rss = "2.1"
ureq = "3"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }

# force scrollbars, version must match to freya-html
blitz-paint = { version = "=0.3.0-beta.2", features = ["scrollbars"] }

[target.'cfg(windows)'.dependencies]
inno = { version = "0.6" , features = ["extract"]}

[features]
debug = ["freya/devtools"]
